"""
AI-Driven Verilog Module Generator
Uses LLM to convert natural language descriptions to synthesizable Verilog RTL.
Author: Kushal Pitaliya
"""

import os
import yaml
from pathlib import Path
from typing import Optional


class VerilogGenerator:
    """Generates Verilog modules from natural language descriptions."""

    def __init__(self, config_path: str = "config/prompts.yaml"):
        self.config = self._load_config(config_path)
        self.api_key = os.getenv("OPENAI_API_KEY")

    @staticmethod
    def _load_config(path: str) -> dict:
        config_file = Path(path)
        if not config_file.exists():
            raise FileNotFoundError(f"Config not found: {path}")
        with open(config_file) as f:
            return yaml.safe_load(f)

    def generate_module(
        self,
        description: str,
        module_name: str,
        inputs: list[str],
        outputs: list[str],
        requirements: Optional[str] = None,
    ) -> str:
        """Generate a Verilog module from a natural language description."""
        prompt_cfg = self.config["verilog_generation"]
        user_prompt = prompt_cfg["user_template"].format(
            description=description,
            module_name=module_name,
            inputs=", ".join(inputs),
            outputs=", ".join(outputs),
            requirements=requirements or "None specified",
        )
        return self._call_llm(prompt_cfg["system"], user_prompt)

    def generate_testbench(self, module_code: str, num_tests: int = 5) -> str:
        """Generate a testbench for an existing Verilog module."""
        prompt_cfg = self.config["testbench_generation"]
        user_prompt = prompt_cfg["user_template"].format(
            module_code=module_code,
            num_tests=num_tests,
        )
        return self._call_llm(prompt_cfg["system"], user_prompt)

    def fix_bugs(self, module_code: str, sim_output: str) -> str:
        """Analyze simulation errors and generate corrected RTL."""
        prompt_cfg = self.config["bug_correction"]
        user_prompt = prompt_cfg["user_template"].format(
            module_code=module_code,
            sim_output=sim_output,
        )
        return self._call_llm(prompt_cfg["system"], user_prompt)

    def _call_llm(self, system_prompt: str, user_prompt: str) -> str:
        """Call LLM API. Falls back to mock in development."""
        if not self.api_key:
            return self._mock_response(user_prompt)

        try:
            from openai import OpenAI

            client = OpenAI(api_key=self.api_key)
            response = client.chat.completions.create(
                model="gpt-4",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.2,
                max_tokens=2000,
            )
            return response.choices[0].message.content
        except Exception as e:
            raise RuntimeError(f"LLM call failed: {e}")

    @staticmethod
    def _mock_response(prompt: str) -> str:
        """Mock response for development without API key."""
        return (
            "// Auto-generated by AI-EDA Playground\n"
            "// (Mock mode — set OPENAI_API_KEY for real generation)\n"
            f"// Prompt: {prompt[:80]}...\n\n"
            "module example (\n"
            "  input  wire clk,\n"
            "  input  wire rst_n,\n"
            "  output reg  out\n"
            ");\n"
            "  always @(posedge clk or negedge rst_n) begin\n"
            "    if (!rst_n) out <= 1'b0;\n"
            "    else        out <= ~out;\n"
            "  end\n"
            "endmodule\n"
        )
